### ISSUE TITLE
"cabal install" failed

### ISSUE THREAD

**Issue by luckypoem** [konn/Yablog#1]
hi.

root@AR:/usr/local/Yablog# cabal install
Resolving dependencies...
Notice: installing into a sandbox located at /usr/local/Yablog/.cabal-sandbox
Configuring Yablog-0.2.0...
Building Yablog-0.2.0...
Failed to install Yablog-0.2.0
Build log ( /usr/local/Yablog/.cabal-sandbox/logs/Yablog-0.2.0.log ):
cabal: Entering directory '.'
Configuring Yablog-0.2.0...
Warning: 'ghc-options: -threaded' has no effect for libraries. It should only
be used for executables.
Building Yablog-0.2.0...
Preprocessing library Yablog-0.2.0...
cabal: can't find source for SharedTypes in .,
dist/dist-sandbox-849b4d9/build/autogen
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
Yablog-0.2.0 failed during the building phase. The exception was:
ExitFailure 1
root@AR:/usr/local/Yablog#

how to fix it?
thank you!

**Comment by konn** [comment]
Sorry, this package is no longer maintained.
